default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: nerve_wizard_development

test:
  <<: *default
  database: nerve_wizard_test

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  # Add this block below:
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate