default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: nerve_wizard_development

test:
  <<: *default
  database: nerve_wizard_test

production:
  adapter: postgresql
  encoding: unicode
  # Render automatically provides DATABASE_URL; Rails will find it here:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
