default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: nerve_wizard_development

test:
  <<: *default
  database: nerve_wizard_test

production:
  <<: *default
  database: nerve_wizard_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
